name: Deploy main

on:
  push:
    branches:
      - main

concurrency:
  group: main
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  validate:
    name: Validate
    uses: ./.github/workflows/validate.yaml

  sync:
    name: Sync
    needs: [ validate ]
    permissions:
      id-token: write # OIDC authentication with AWS
      contents: read
    uses: ./.github/workflows/sync.yaml
