name: Sync

on:
  workflow_call:
    secrets:
      AWS_ROLE_ARN:
        required: true
      BUCKET_NAME:
        required: true

permissions:
  contents: read

jobs:
  apply:
    name: Apply
    timeout-minutes: 3
    runs-on: ubuntu-latest
    environment: pro
    permissions:
      id-token: write # OIDC authentication with AWS
      contents: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Assume role
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          aws-region: 'eu-west-1'
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: S3 sync
        shell: bash
        run: |
          aws s3 sync pubs/ s3://${VARS_BUCKET_NAME}
        env:
          VARS_BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
